// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtdJya1C7ZGQRSeZVXDGAnCRn91FJXfaw',
    appId: '1:370161722732:web:df2428b8e54a0b14073f49',
    messagingSenderId: '370161722732',
    projectId: 'ai-smart-wallet-93262',
    authDomain: 'ai-smart-wallet-93262.firebaseapp.com',
    storageBucket: 'ai-smart-wallet-93262.firebasestorage.app',
    measurementId: 'G-K79PPM1NE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtNFeMsyYWsVYKfPGxS-37_YXnqK5dtKs',
    appId: '1:370161722732:android:e4e66309ad59dc2c073f49',
    messagingSenderId: '370161722732',
    projectId: 'ai-smart-wallet-93262',
    storageBucket: 'ai-smart-wallet-93262.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi7vJZ7p3GY1jNGYBA-ci7G-kkpl4gdpY',
    appId: '1:370161722732:ios:065d018018ca07c4073f49',
    messagingSenderId: '370161722732',
    projectId: 'ai-smart-wallet-93262',
    storageBucket: 'ai-smart-wallet-93262.firebasestorage.app',
    iosBundleId: 'com.mirkocolombo.aismartwallet.aiSmartWallet',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi7vJZ7p3GY1jNGYBA-ci7G-kkpl4gdpY',
    appId: '1:370161722732:ios:065d018018ca07c4073f49',
    messagingSenderId: '370161722732',
    projectId: 'ai-smart-wallet-93262',
    storageBucket: 'ai-smart-wallet-93262.firebasestorage.app',
    iosBundleId: 'com.mirkocolombo.aismartwallet.aiSmartWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtdJya1C7ZGQRSeZVXDGAnCRn91FJXfaw',
    appId: '1:370161722732:web:912b07f85dde8bf9073f49',
    messagingSenderId: '370161722732',
    projectId: 'ai-smart-wallet-93262',
    authDomain: 'ai-smart-wallet-93262.firebaseapp.com',
    storageBucket: 'ai-smart-wallet-93262.firebasestorage.app',
    measurementId: 'G-WHCJQNR9MS',
  );
}
